server:
  port: 8077
  servlet:
    context-path: /
  tomcat:
    max-threads: 100
spring:
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      first:
        url: jdbc:mysql://localhost:3306/record-life?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=Hongkong
        username: shadow
        password: shadow

mybatis-plus:
  mapper-locations: classpath:/mapper/*.xml
  type-aliases-package: com.shadow.common.entity.photo