server:
  port: 8077
  servlet:
    context-path: /
  tomcat:
    max-threads: 100
spring:
  datasource:
    dynamic:
      primary: master
      datasource:
        master:
          url: jdbc:mysql://localhost:3306/record-life?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=Hongkong
          username: shadow
          password: shadow
          driverClassName: com.mysql.cj.jdbc.Driver
        second:
          url: jdbc:mysql://10.80.210.132:3306/xinsec_security?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=Hongkong
          username: developer
          password: 123456
          driverClassName: com.mysql.cj.jdbc.Driver
  autoconfigure:
    # 使用的数据源是动态的，所以需要排除自动配置数据源的类DataSourceAutoConfiguration，而用的是连接池的数据源，所以需要排除DruidDataSourceAutoConfigure
    exclude: com.alibaba.druid.spring.boot.autoconfigure.DruidDataSourceAutoConfigure

mybatis-plus:
  mapper-locations: classpath:/mapper/*.xml
  type-aliases-package: com.shadow.common.entity.photo
